### ISSUE TITLE
Fix CLI dependency install

### ISSUE THREAD

**Issue by jaeddy** [ga4gh/gh-openapi-docs#10]
This package itself is intended to be used as a CLI. A couple of its dependencies (`swagger-repo` and `redoc-cli`) are also CLIs. I'm not sure how to configure `package.json` so that these dependencies are installed and available by the package in associated scripts (i.e., `bundle.js` and `redoc-ui.js`).

The functionality provided by `swagger-repo` might soon be unnecessary, and the ReDoc CLI might be replaceable with the [**redoc** library](https://github.com/Redocly/redoc)... but I'm not entirely sure how to implement the latter.

**Comment by jb-adams** [comment]
The `redoc` library has 'API Console' on their roadmap, which might be what we're looking for (unfortunately, it looks like it's not ready yet). One possible solution could be to install the CLI tools in the package `node_modules` itself (non-globally), and then run the scripts through `npx`. It's not ideal, but would achieve some encapsulation (no global installs, all scripts associated with npm/npx)

**Comment by jaeddy** [comment]
Thanks, @jb-adams - I'll take a closer look!

**Comment by jaeddy** [comment]
This setup works fine in Travis for repos using the package:
```
      before_script:
      - npm install -g @redocly/openapi-cli && npm install -g redoc-cli
      - npm install -g @ga4gh/gh-openapi-docs
      script:
      - gh-openapi-docs
```

Seems simple enough to me for now (though we could consider switching to `npx` at some point). Closing this issue.
