### ISSUE TITLE
Create Org scope on npm

### ISSUE THREAD

**Issue by tschaffter** [ga4gh/gh-openapi-docs#17]
and add this package to it: @ga4gh/gh-openapi-docs

The npm organization `ga4gh` already exists. Does it belong to GA4GH?
https://www.npmjs.com/org/ga4gh

**Comment by jb-adams** [comment]
@tschaffter thanks for raising this. @jaeddy do you know the owner of this org? I'll raise to secretariat to see if we can track down the owner

**Comment by jaeddy** [comment]
@jb-adams I have no idea — would definitely be worth checking into.

**Comment by tschaffter** [comment]
@jb-adams @jaeddy I've tried to get the contact information using the command `npm team ls org-js`, but the endpoint called under the hood is not public. I have filled in npmjs.org Contact Us for to ask how to get the contact information of the user who created the npmjs.org organization "ga4gh". I'll update this ticket once I get a reply.

**Comment by tschaffter** [comment]
The owner of the npmjs.org Organization "ga4gh" is Marc Fiume. I have added you in cc to my reply to Mark.

**Comment by jb-adams** [comment]
Thanks @tschaffter ! I've responded in the thread. Basically, with the `ga4gh` org in `npm` or any package/code index, we'd like to have at least one Secretariat member as an owner, plus other GA4GH members who contribute on a regular basis as owners. So Thomas, James, Marc, Rishi, and myself should all be owners

**Comment by tschaffter** [comment]
@jb-adams It looks like you successfully obtained owner account for the npmjs Organization "ga4gh". Is Marc Fiume actually contributing to ga4gh? If not, he is conserving his `Owner` status for the npmjs Organization "ga4gh"?

**Comment by jaeddy** [comment]
@tschaffter not sure if Marc or his team are actively publishing to npm at the moment, but as CEO of [DNAstack](https://github.com/DNAstack), he's definitely a big contributor to GA4GH. Seems like most of their stack is Java, but they have at least [one project](https://github.com/DNAstack/ddap-libraries) that looks like it might be worth making available through npm under the "ga4gh" org.

**Comment by jb-adams** [comment]
@tschaffter @jaeddy that's right, DNAstack might be contributing to `npm` in the future. James, should I make you an owner as well?

**Comment by jaeddy** [comment]
Thanks, @jb-adams! Looking at the roles/permissions defined for `npm`, I'm not sure that I need to be anything more than a `member`:

![image](https://user-images.githubusercontent.com/5033229/85218359-6023c780-b34e-11ea-92b6-12e85966f41d.png)

But, if it seems like it might be helpful to add me as owner or admin, that's fine with me too.

**Comment by tschaffter** [comment]
@jb-adams One `Admin` user at Sage may be useful to manage npmjs Teams, but I could also ask for this permission when it's effectively needed.

**Comment by jb-adams** [comment]
@tschaffter you're an owner, which should include all `admin` privileges as well. @jaeddy I can invite you as a `member`, can you let me know your `npm` handle? If there's a need to upgrade you to `admin` or `owner` we can do that as well.

**Comment by jaeddy** [comment]
Thanks, @jb-adams! My npm handle is the same ("jaeddy"). How do we go about actually adding a package to the org? And am I understanding correctly that the resulting 'scope' for the package would be `@ga4gh/gh-openapi-docs`, or is that something we need to configure separately?

**Comment by jb-adams** [comment]
@jaeddy invited you, also published the package to [@ga4gh/gh-openapi-docs](https://www.npmjs.com/package/@ga4gh/gh-openapi-docs). The above PR will allow subsequent  builds to publish under `@ga4gh` by default

**Comment by jaeddy** [comment]
Sweet! I think we can officially call this issue closed. 🙂
