### ISSUE TITLE
Add GA4GH Theme

### ISSUE THREAD

**Issue by jb-adams** [ga4gh/gh-openapi-docs#25]
Right now, it looks like the built docs have the default `redoc` themes and logos. It might be good to spruce up the GA4GH docs with our own logo and color scheme.

**Comment by jaeddy** [comment]
The project isn't intended to be specific to GA4GH, but I'm happy to make that the default theme. 🙂

**Comment by jaeddy** [comment]
Actually, taking a closer look, logo is something that gets set in the OpenAPI spec, so not part of the build. We could probably provide an example, or even a template for a yaml that could get integrated into the main spec.

In terms of other theme elements, they seem less trivial to [customize](https://github.com/Redocly/redoc#redoc-options-object). We should eventually be able to support standard GA4GH branding (e.g., [fonts, colors, used on WS sites](https://github.com/ga4gh-duri/ga4gh-duri.github.io)) — but might not prioritize for now.

**Comment by jaeddy** [comment]
I found a useful tool, [**redoc-editor**](https://github.com/pointnet/redoc-editor), that lets you customize most of the ReDoc theme within a React site. I did some initial tweaking based on the ga4gh.org styles — though, the branding is still somewhat subtle.

![image](https://user-images.githubusercontent.com/5033229/84352623-87baa900-ab72-11ea-87ac-494bb93e4747.png)

I haven't quite figured out how to incorporate these theme settings into the docs build, but stashing some of the options here for reference...

```json
{
    "untrustedSpec": true,
    "pathInMiddlePanel": true,
    "theme": {
        "colors": {
            "primary": {
                "main": "rgba(27, 117, 187, 1)",
                "light": "rgba(99, 162, 211, 1)",
                "dark": "rgba(6, 71, 121, 1)",
                "contrastText": "#fff"
            },
            "success": {
                "main": "rgba(141, 198, 62, 1)",
                "light": "rgba(201, 240, 147, 1)",
                "dark": "rgba(83, 136, 10, 1)",
                "contrastText": "#000"
            },
            "warning": {
                "main": "rgba(250, 166, 51, 1)",
                "light": "rgba(255, 203, 131, 1)",
                "dark": "rgba(173, 101, 1, 1)",
                "contrastText": "#000"
            },
            "error": {
                "main": "rgba(227, 74, 58, 1)",
                "light": "rgba(255, 151, 140, 1)",
                "dark": "rgba(155, 20, 6, 1)",
                "contrastText": "#000"
            },
            "http": {
                "get": "rgba(107, 189, 91, 1)"
            }
        },
        "typography": {
            "links": {
                "color": "rgba(144, 98, 165, 1)",
                "visited": "rgba(144, 98, 165, 1)",
                "hover": "rgba(159, 121, 176, 1)"
            }
        },
        "rightPanel": {
            "backgroundColor": "rgba(66, 66, 66, 1)",
            "textColor": "rgba(255, 255, 255, 1)"
        },
        "codeSample": {
            "backgroundColor": "rgba(34, 31, 31, 1)"
        }
    }
}
```
