### ISSUE TITLE
Rename master branch to "main"

### ISSUE THREAD

**Issue by tschaffter** [ga4gh/gh-openapi-docs#67]
"main" is now the name of the default branch when creating a repository.

**Comment by tschaffter** [comment]
@jb-adams If you want to give me admin access to this repository, I can take care of actions like renaming the default branch, configuring protected branches, etc. Every feature that I contribute to would be submitted through a PR created from a feature branch of my fork.

**Comment by jb-adams** [comment]
invite sent, please modify as needed, thanks!

**Comment by tschaffter** [comment]
I created the branch `main` and removed `master`. The branch `develop` remains the default branch.
